qiime2/package-integration

2022.2/staged/core/conda_build_config.yaml, 2022.2/tested/conda_build_config.yaml, 2022.4/staged/core/conda_build_config.yaml, 2022.4/tested/conda_build_config.yaml
this pin is temporary, just sorting out all sorts of build issues.
=> dep: pin biom-format

2022.4/staged/community/conda_build_config.yaml, 2022.4/staged/community/data.yaml
and ignore q2-assembly for now
=> maint: bulk update community distro

2022.4/staged/community/conda_build_config.yaml, 2022.4/staged/core/conda_build_config.yaml, 2022.4/tested/conda_build_config.yaml
=> dep: hard pin unifrac (and add unifrac-binaries)

2022.4/staged/community/data.yaml, 2022.8/staged/community/conda_build_config.yaml, 2022.8/staged/community/data.yaml
=> dev-bump: 2022.8 community distro (omnibus PR)

.github/actions/test-package/action.yml
This PR modifies the file name expansion to resolve failing package builds
=> tst: file name expansion

.github/actions/test-package/action.yml
Reverts qiime2/package-integration#378
=> Revert "tst: more file expansion testing"

.github/actions/test-package/action.yml
Reverts qiime2/package-integration#377
=> Revert "tst: file name expansion"

.github/actions/test-package/action.yml
Reverts qiime2/package-integration#376
=> Revert "TST: try using mambabuild instead"

.github/actions/test-package/bin/run_tests.py
This PR installs any additional test requirements for each package and will hopefully resolve the community distro build failures for 2022.11.
=> bug: adding test requirements

.github/actions/test-package/action.yml
Reverts qiime2/package-integration#387
=> Revert "bug: macos doesn't have write access by default"

.github/actions/test-package/action.yml
this PR attempts to resolve the osx permissions issues by adding sudo commands for each action that contains write requirements.
=> test: adds sudo commands for osx permissions

.github/actions/configure-conda/action.yml, .github/actions/test-package/action.yml, .github/actions/test-package/bin/run_tests.py
This restores the changes that were reverted from PR #398
=> restore: testing mods for build failures

.github/actions/configure-conda/action.yml
adding a print statement to check if this branch is even being hit
=> debug: is this working?

.github/actions/configure-conda/action.yml, .github/actions/test-package/bin/run_tests.py
adding the defaults channel to see if this will resolve the conflicts for diversity and vsearch in the latest builds
=> debug: let's try this again

.github/workflows/ci-build-metapackage.yaml
Reverts qiime2/package-integration#410
=> Revert "debug: changing q2-channel"

2022.11/staged/community/conda_build_config.yaml, 2022.11/staged/core/conda_build_config.yaml, 2022.11/tested/conda_build_config.yaml
Reverts qiime2/package-integration#420
=> Revert "pin: r-base 4.2.0"

2022.11/staged/core/conda_build_config.yaml, 2022.11/tested/conda_build_config.yaml
Reverts qiime2/package-integration#451
=> Revert "Revert "pin: r_base for core distro""

.github/actions/configure-conda/action.yml
Move yq above conda-build just to see if there is some order of operations stuff happening
=> Move where we install yq up a bit just in case

.github/actions/configure-conda/action.yml
Reverts qiime2/package-integration#458
=> Revert "Move where we install yq up a bit just in case"

2022.11/staged/core/conda_build_config.yaml
Reverts qiime2/package-integration#491
=> Revert "Update conda_build_config.yaml"

2022.11/tested/conda_build_config.yaml
this will get reverted once we update w/skbio and scipy
=> pin: biom-format pin for diversity-lib failure

2023.5/staged/community/conda_build_config.yaml, 2023.5/staged/community/data.yaml, 2023.5/staged/community/meta.yaml.jinja
adds 2023.5 folder with stripped CBCs and new version strings for community distro
=> dev-bump: 2023.5 community cbc
